### ISSUE TITLE
MDC with angular

### ISSUE THREAD

**Issue by ghost** [mdc-dart/material_components_web#11]
I am looking for MDC that works with the flutter patterns.

This will make maybe 90% of all a apps code work on flutter and web.

I could adapt the MDC work you have done but figured I should ask first

**Comment by thosakwe** [comment]
Hi, such a thing does not exist at this point. These components are designed to work with Angular, which is fundamentally different from Flutter. I doubt there will be anything like Flutter on the Web soon.

I've had luck both with this library and with Polymer, but the current version of Polymer does not support Dart.

**Comment by ghost** [comment]
Yes i know they are designed to work with angular. Thats the problem.

i found a few things that are flutter for web.
1. One that takes the flutter code, pathes it and it runs on html / web. It does work.

2. Then there is the built_value dart package which allows a base to built up to immutable structures and so basically allows ou to build 90% of your dart code to be shred on flutter and web. 
https://github.com/google/built_value.dart/tree/master/example
From here follow the dependencies paths are you arrive at a cross platform reflux / pub sub package. Bingo, you are getting very close now to just simple GUI with all the logic being cross platorm.


I run away away from Polymer. Used it before but it just not going anyware

The MDC for web is now way better than using Polymer and does nto trap you - thats a godo thing
https://github.com/material-components/material-components-web

I can get something going and try a few things out.
